Fix require() error - use ES6 imports instead
ERROR: "Can't find variable: require" in browser runtime

PROBLEM:
- Used require() for chaikinSmoothMultiple and simplifyPolyline
- require() is CommonJS, doesn't work in browser/TypeScript

SOLUTION:
- Added proper ES6 imports at top of file:
  - import { chaikinSmoothMultiple } from '../ChaikinSmoothing'
  - import { simplifyPolyline } from '../PolylineSimplifier'
- Removed require() calls from optimization code

Now warm segment optimization will run without errors!